1. Importing numpy and using it as np for ease.

In [183]:
import numpy as np

2. Print numpy version

In [184]:
print(np.__version__)

1.19.4


3. Printing numpy array of 10

In [185]:
ar1d = np.arange(15)
ar1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

4. Converting ar1d to 2D array (using -1 to fill the matrix)

In [186]:
ar2d = ar1d.reshape(3,-1)
ar2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

5. Converting ar1d to 3D array

In [187]:
ar3d = ar1d.reshape(1,5,3)
ar3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]]])

6. shape of 3d array

In [188]:
ar3d.shape

(1, 5, 3)

7. print dimension of array

In [189]:
ar3d.ndim

3

8. print datatype of array

In [190]:
ar3d.dtype.name

'int64'

9. print item size of array

In [191]:
ar3d.size

15

10. printing 2d zeros (default prints float64)

In [192]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

11. printing 2d ones

In [193]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

12. the function empty creates an array whose initial content is random and depends on the state of the memory

In [194]:
np.empty( (2,3) ) 

array([[2.07955588e-312, 2.07955588e-312, 2.12199579e-312],
       [2.12199579e-312, 2.14321575e-312, 2.18565567e-312]])

13. arranging 2D array  with inciment of 5

In [195]:
np.arange( 10, 30, 5 )

array([10, 15, 20, 25])

14. printing bytes of number

In [196]:
ar3d.itemsize

8

15. linspace creates equal distribution with number passsed

In [197]:
np.linspace(1,3,9)

array([1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 , 2.75, 3.  ])

16. creating boolean array

In [198]:
np.array([True], dtype=bool)

array([ True])

17. Reverse an Array

In [199]:
print(ar1d)
np.flipud(ar1d)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


array([14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

18. Printing Arrays

In [200]:
print (ar1d)
print()
print (ar2d)
print()
print (ar3d)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]]


19. Adding two numpy arrays

In [201]:
A = np.array([3,5,6])
B = np.array([2,4,8])
A+B

array([ 5,  9, 14])

20. Mupltiplying arrays

In [202]:
print(A*2)
print()
print(ar2d*3)

[ 6 10 12]

[[ 0  3  6  9 12]
 [15 18 21 24 27]
 [30 33 36 39 42]]


21. Comparing two numpy arrays

In [203]:
comparision = A == B
comparision.all()

False

22. Printing odd arrays from a numpy array

In [204]:
odd = ar1d % 2 == 1
ar1d[odd]

array([ 1,  3,  5,  7,  9, 11, 13])

23. Common values in two arrays

In [205]:
C= np.array([2,3,7,8,9,14])
D= np.array([1,3,4,5,9,11])
print(np.intersect1d(C, D)) 

[3 9]


24. copy numpy array in to new variable

In [206]:
E = C.copy()
E

array([ 2,  3,  7,  8,  9, 14])

25. Sorting Arrays

In [207]:
arns = np.array([3,1,-1,10,-10,30,5,3.5])
np.sort(arns)

array([-10. ,  -1. ,   1. ,   3. ,   3.5,   5. ,  10. ,  30. ])

26. Concetinating two arrays

In [208]:
np.concatenate((C,D))

array([ 2,  3,  7,  8,  9, 14,  1,  3,  4,  5,  9, 11])

27. Filling an array with zeros

In [209]:
ar3d.fill(0)
ar3d

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

28. Resizing an array

In [210]:
np.resize(C,(2,3))

array([[ 2,  3,  7],
       [ 8,  9, 14]])

29. Ravel in numpy 2d array

In [211]:
np.ravel(ar2d)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

30. Transpose on a 3d array

In [212]:
a3d = np.arange(15).reshape(3,1,5)
np.transpose(a3d)

array([[[ 0,  5, 10]],

       [[ 1,  6, 11]],

       [[ 2,  7, 12]],

       [[ 3,  8, 13]],

       [[ 4,  9, 14]]])

31. Flatten a 3d array

In [213]:
a3d.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

arns

In [214]:
np.amin(arns)

-10.0

33. Finding maximum of arns array

In [215]:
np.amax(arns)

30.0

34. Finding mean of arns array

In [216]:
np.mean(arns)

5.1875

35. Finding median of arns array

In [217]:
np.median(arns)

3.25

36. Rounding a decimal array

In [218]:
F = np.array([2.34,3.5,9.9,4.6,5.8])
np.around(F)

array([ 2.,  4., 10.,  5.,  6.])

37. Saving and loading an array

In [219]:
l1 = np.arange(3,10)
np.save("a1", l1)

In [220]:
a = np.load('a1.npy')
a

array([3, 4, 5, 6, 7, 8, 9])

38. Search Sorting values in an array

In [221]:
np.searchsorted(a,4)

1

39. Generating random 3D array 

In [222]:
np.random.rand(5,1,2)

array([[[0.9727534 , 0.46930374]],

       [[0.83753663, 0.14452993]],

       [[0.63327276, 0.97518814]],

       [[0.38430424, 0.09337359]],

       [[0.73199274, 0.59190686]]])

40. Using numpy condition in array

In [223]:
arr = np.arange(10,21)
np.where(arr<12,arr,arr-1)

array([10, 11, 11, 12, 13, 14, 15, 16, 17, 18, 19])

41. Counting a value in an array

In [224]:
tarr = np.array(['abc','bcd','cde','efg'])
np.char.count(tarr,'c')

array([1, 1, 1, 0])

42. Filtering values in an array

In [225]:
bol = [False,True,True,False]
tarr[bol]

array(['bcd', 'cde'], dtype='<U3')

43. Finding the character that endswith in an array

In [226]:
np.char.endswith(tarr,'g')

array([False, False, False,  True])

44. Splitting an array into two

In [227]:
np.array_split(arr,2)

[array([10, 11, 12, 13, 14, 15]), array([16, 17, 18, 19, 20])]

45.Iterating a numpy array

In [228]:
arrnew = np.arange(2,15)
for x in arrnew:
  print(x)

2
3
4
5
6
7
8
9
10
11
12
13
14


46.Replacing a value in an array

In [229]:
arrnew[0]=1
arrnew

array([ 1,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

47. Printing specific values in an array

In [230]:
print (arrnew[2:7])

[4 5 6 7 8]


48. Checking value at a specific index on arrray



In [231]:
print (arrnew[10])

12


49.Chaning type of array from one type to another

In [232]:
arrtyp = arr.astype(str)
type(arrtyp)

numpy.ndarray

50.Checking image of an array

In [233]:
arrtyp.imag

array(['', '', '', '', '', '', '', '', '', '', ''], dtype='<U21')